a_questions = {
1:["What month is the first month of Autumn?", 9],
2:["What month holds International Womens Day?", 3],
3:["How many feet are there in a meter?", 3],
4:["What month was Apple founded?", 4],
5:["Summer solstice in the UK occurs in what month?", 6],
6:["What is the highest awarding of Michelin Stars?", 3],
7:["In 'The Little Mermaid' how many sister's does Ariel have?", 6],
8:["What is the highest single digit prime number?", 7],
9:["What's the 2nd decimal digit of Pi? (i.e not including the 3)", 4],
10:["How many faces does a 3D trapezium have?", 6],
11:["How many years did World War 2 last for?", 6],
12:["How many hearts does a squid have?", 3],
13:["How many books are in the Harry Potter series?", 7],
14:["Ed Sheeran released 'Shape of You' in 201_", 7],
15:["What value is XIV in roman numberal?", 14],
16:["Complete the formula. America has 10 * n states. What is n?", 5],
17:["What is a perfect gymnastics score?", 10],
18:["The Beatles wanted to know 'Will you need me, will you feed me, when I'm 6_'", 4],
19:["How many engines are there on a Boeing 747?", 4],
20:["According to the Commodores, once, twice, _ times a lady?", 3],
21:["The final World Cup of the 20th Century was held in 199_", 8],
22:["What number can be spelled with the same number of letters as itself?", 4],
23:["How many minutes does it take sunlight to reach earth?", 8],
24:["What number produces resulting digits that sum to the number when multiplied by a single-digit?", 9],
25:["The inner ring on a dart board multiples your score by how many times?", 3],
26:["How many zero's are in 1 Trillion?", 12],
27:["What number is sete in Portugese?", 7],
28:["In the hit 1996 song, how many Lions are on the shirt?", 3],
29:["Oasis released 'Definitely Maybe' in 199_?", 4],
30:["'I Got _ On It' is the title of a track by Luniz.", 5],

}

b_questions = {
1:["Possesion is commonly considered how many tenths of the law?", 9],
2:["The value in Cricket when a ball runs along the ground and to the boundary", 4],
3:["The first half of a Golf Course is commonly referred to as the front-_.", 9],
4:["The difference in age between UK and US for legally purchasing alcohol.", 3],
5:["The average shoe size for Men in the UK.", 9],
6:["The average shoe size for Women in the UK", 6],
7:["In how many decades have the Rolling Stones had a UK Number 1 album?", 6],
8:["How many Kilometers deep is the deepest part of the Ocean?", 11],
9:["How many days does Burning Man festival run for?", 9],
10:["Nintendo launced the GameBoy in 198_",9],
11:["The total possible values in a 4-bit system.", 16],
12:["President Obama was first appointed into Office as the President of The United States in 20_ _.", 9],
13:["An Olympic swimming pool is _0 meters long.", 5],
14:["Excluding spin-offs, the numbers of years between the first and last published Harry Potter books.", 10],
15:["Apple launched the first Macintosh in 198_", 4],
16:["How many kilometers has a 40Km/h train gone in 15 minutes?", 10],
17:["How many players are there on a Netball team?", 7],
18:["How many outfield players are there on a Ice Hockey team?", 6],
19:["How many Academy Award nominations has Morgan Freeman received?", 5],
20:["How many Academy Award nominations has Russell Crowe received?", 3],
21:["How many Academy Award nominations has Emma Thompson received?", 5],
22:["How many years did Tony Blair serve as Prime Minister in the UK?", 10],
23:["What number lies directly opposite to 2 on a standard die?", 5],
24:["How many inches wide is a standard A4 piece of paper?", 8],
25:["In which century was the Spanish Armada?", 16],
26:["In boxing, how many male quintuple champions are there?", 5],
27:["In boxing, how many female quintuple champions are there?", 2],
28:["What is the letter K worth in scrabble?", 5],
29:["How many major Airports are there in London?", 6],
30:["The Album Zeppelin IV contains how many tracks?", 8],
31:["The Berlin Wall collapsed in 198_?",9],
32:["'Engine, engine, number __' is a lyric from 'Be Faithful' by 'Fatman Scoop and Crooklyn Clan'", 9],
33:["Alice In Wonderland was published in November 196_", 5],
34:["The £2 coin was introduced in 199_", 8],
35:["'_ out of 10' is the title of a track from Drake's Scorpion album.", 8],
36:["The original Woodstock was held in 196_?", 9],

}

c_questions = {

2:["Complete the year. Wembley hosted the first FA Cup final in 19_ _.", 23],
3:["Jimi Hendrix wrote the song 'If 6 Was _'", 9],
4:["What is the UK speed limit difference of a car on a Motorway vs Single Carriageway in MPH?", 10],
5:["Diana, Princess of Wales sadly lost her life in 19_ _", 97],
6:["The houses of parliment started construction in 18_ _", 36],
7:["Mount everest is 88 _ _ meters elevation.", 49],
8:["The orbital period of the earth is 5_ _, 000 minutes.", 26],
9:["The UK's first female prime minister was appointed in 19_ _", 79],
10:["David Beckham scored how many goals for England?", 17],
11:["Martin Luther King gave his 'I have a dream' speech in 19_ _", 63],
12:["Rocky 2 was released in cinemas in 19_ _", 79],
13:["Arnold Schwarzenger's political career came to an end in 20_ _", 11],
14:["Aretha Franklin covered the song 'Respect' in 19_ _", 67],
15:["Remi took 4 business trips to New York, 2 of which needed connecting out-bound flights. How many planes has remi flown on?", 10],
16:["What age can you legally get a job in the UK?", 14],
17:["NASCAR was founded in 19_ _", 48],
18:["Kinder Scount in the Peak District has a elevation of 6_ _ meters.", 36],
19:["The Rolling Stones have how many No. 1 Albums in the UK?", 13],
20:["What is the first double digit in the Fibonacci sequence?", 13],
21:["The Aston Martin DB9 features what size of V engine?", 12],
22:["How many countries are there in South America?", 12],
23:["If you're travelling North-East, what degree heading are you travelling?", 45],
24:["How many divisions of the People's Republic of China are classified as provinces?", 23],
25:["D-Day was carried out on 6th June in 19_ _", 44],
26:["The final Apollo mission in December 7, 1972 was Apollo _ _.", 17],
27:["Excluding a tie-break, how many holes has a winner of The Masters played?", 72],
28:["The popular book by George Orwell was called 19_ _.", 84],
29:["The final number to the sequence entered into a computer in the TV Show 'Lost'", 42],
30:["In english law, what is the smallest number of people to constitute a riot?", 3],
31:["How many rows of Stars are on the American Flag?", 9],
32:["Letter E tiles make up how many of the 100 tiles in a game of scrabble?", 12],
33:["'Tomorrow Never Dies' was released in 199_", 7],
34:["Finish this year. Tom hanks was born in 19_ _?", 56],
35:["How many teeth does a bear have?", 42],
36:["How many stars are on the Paramount Studios Logo?", 22],
37:["How many weeks was Wayne's World filmed in?", 2],
38:["How old was Bill Gates when he founded Microsoft?", 19]



}

d_questions = {
1:["What is the minimum circumference of a Regulation Size 5 Football in centimeters?",68],
2:["The circumference of Earth is 40,0_ _ Km", 75],
3:["How many bones are there in a foot?", 26],
4:["How fast in Km/h do you need to travel to reach 5Km in 10 minutes?", 30],
5:["How many weeks are approximately in 2 years?", 104],
6:["Finish this total. Japan has 6,8 _ _ islands.", 52],
7:["In Celcius, the lowest ever recorded temperature on Earth is minus __˚C?", 82],
8:["In Celcius, The highest ever recorded temperature on Earth is __˚C?", 57],
9:["Finish this length. The tallest man on Earth measured 2__cm.",72],
10:["Construction on the Brooklyn Bridge began in 18_ _", 69],
11:["Then Oldest Working Railway, excluding cable systems, was founded in 17__",58],
12:["Ronaldinho joined Barcelona in 2003 for a transer fee of how many million Euros?", 30],
13:["The Men's 100m World Record currently stands at 9._ _s", 58],
14:["Michael Phelps holds how many Olympic Gold Medals?", 23],
15:["How many Olympic Medals does Larisa Latynina hold?", 18],
16:["What is the maximum possible break in snooker?", 155],
17:["How many sites does France have on the Unesco World Heritage Site list?", 39],
18:["Finish this year. The Battle of The Dunes was in 16_ _", 58],
19:["What is the top speed of a Cessna 172 in MPH?", 187],
20:["Finish this year. The black death begain it's spread around Afro-Eurasia in 13_ _", 46],
21:["How old was Julius Cesar when he died?", 55],
22:["Albert Einstein propsed his E=mc**2 concept in 19_ _", 5],
23:["The Statue of Liberty was constructed in 18_ _.", 76],
24:["How many elements are on the Periodic Table?", 118],
25:["How many elements of the Periodic Table begin with the letter Z?", 2],
26:["The moon is how many thousand miles away from the Earth?", 240],
27:["What number on the Beaford scale, represents a Hurricane?", 12],
28:["On March 12, 2022 the Eifell tower became how many meters high.", 330],
29:["A googol has how many zeros?", 100],
39:["How many rivers are there in Jamaica?", 120],



}
